base_url = "https://infinitivewitch.github.io"
theme = "neoathame"

[extra.social]
name = "Infinitive Witch"
avatar = "assets/infinitivewitch.png"
shortbio = "∞"

[extra.social.links.1]
service = "github"
username = "@infinitivewitch"
url = "https://github.com/infinitivewitch"

[extra.social.links.2]
service = "anilist"
username = "@infinitivewitch"
url = "https://anilist.co/user/infinitivewitch"

[extra.social.links.3]
service = "discord"
username = "infinitivewitch #5530"
url = "https://discordapp.com/users/1088800006959530056"

[extra.social.links.4]
service = "mastodon"
username = "@infinitivewitch@fe.disroot.org"
url = "https://fe.disroot.org/@infinitivewitch"
